#!/usr/bin/env python3
# Stands in for LibreOffice's --convert-to pdf in this sandbox, where the real
# one cannot run. Writes a valid one-page PDF next to the requested outdir.
import sys, os
argv = sys.argv[1:]
outdir = argv[argv.index('--outdir') + 1] if '--outdir' in argv else '.'
src = argv[-1]
name = os.path.splitext(os.path.basename(src))[0] + '.pdf'
body = b"BT /F1 24 Tf 72 700 Td (CONVERTED CONTRACTOR AGREEMENT) Tj ET"
objs = [b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(body)).encode() + b" >>\nstream\n" + body + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]
out = b"%PDF-1.4\n"; offs = []
for i, o in enumerate(objs, 1):
    offs.append(len(out)); out += f"{i} 0 obj\n".encode() + o + b"\nendobj\n"
x = len(out)
out += f"xref\n0 {len(objs)+1}\n0000000000 65535 f \n".encode()
for off in offs: out += f"{off:010d} 00000 n \n".encode()
out += f"trailer\n<< /Size {len(objs)+1} /Root 1 0 R >>\nstartxref\n{x}\n%%EOF".encode()
open(os.path.join(outdir, name), 'wb').write(out)
